[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shine_users = "5dFcWDNp42Xn9Vv4oDMJzM4obBJ8hvDuAtPX54fT5L3t"      #тут надо если что обновлять
shine_payments = "92sgkgx7KHpbhQu81mNGHaKa7skJB7esArVdPM7paDSW"          #тут надо если что обновлять


[programs.devnet]
shine_users = "5dFcWDNp42Xn9Vv4oDMJzM4obBJ8hvDuAtPX54fT5L3t"            #тут надо если что обновлять
shine_payments = "92sgkgx7KHpbhQu81mNGHaKa7skJB7esArVdPM7paDSW"              #тут надо если что обновлять


[workspace]
members = [
    "programs/shine_users",
    "programs/shine_payments",
]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"#"http://127.0.0.1:8899"                      # это в какую сеть деплоит по умолчанию
wallet = "~/.config/solana/id.json"     # а это с какого кошелько спишутся средства за деплой

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"







